from typing import Tuple, Callable

from .util import Params, DynamicState, smooth_step

from .wake_deflection.gauss import calculate_transverse_velocity, wake_added_yaw, yaw_added_turbulence_mixing
import jax.numpy as jnp
from jax import lax
import jax
jax.config.update("jax_enable_x64", True)

def average_velocity_jax(v, method="cubic-mean"):
    if method == "simple-mean":
        return jnp.mean(v, axis=(-2, -1), keepdims=True, dtype=v.dtype)
    if method == "cubic-mean":
        m3 = jnp.mean(v**3, axis=(-2, -1), keepdims=True, dtype=v.dtype)
        return jnp.cbrt(m3)                 # exact libm cbrt, matches Torch
    raise ValueError


def sequential_solve_step(
        state: DynamicState,
        ii: int,
        params: Params,
        thrust_function: Callable,
        axial_induction_func: Callable,
        velocity_model: Callable,
        deflection_model: Callable,
        turbulence_model: Callable ,
        combination_model: Callable,
        yaw_angles: jnp.array,
        tilt_angles: jnp.array,
        enable_secondary_steering: bool,
        enable_transverse_velocities: bool,
        enable_yaw_added_recovery: bool,
        x_coord, y_coord, z_coord,
        x_c, y_c, z_c,
        u_init, dudz_init,
        ambient_ti
        ) -> Tuple[DynamicState, None]:
    """
    JAX-based sequential solver compatible with the Gauss-Curl Hybrid model
    1. Extract local velocity components at turbine i
    2. Calculate C_t and axial induction
    3. Calculate secondary steering: compute added_yaw from transverse velocities and add to yaw_i
    4. Calculate wake deflection using effective yaw
    5. Calculate transverse wake velocities generated by turbine i
    6. Calculate yaw added recovery: update TI field based on transverse wake velocities
    7. Calculate velocity deficit and combine it with the existing wake field
    8. Return the updated state to be used by turbine i + 1
    """

    # Unpack state tensors
    turb_u_wake, turb_inflow, ti, v_sorted, w_sorted = (
        state.turb_u_wake, state.turb_inflow, state.ti,
        state.v_sorted, state.w_sorted
    )



    # Constants for turbine ii
    B, T, Ny, Nz = x_coord.shape

    x_i = lax.dynamic_index_in_dim(x_c, ii, axis=1, keepdims=True)
    y_i = lax.dynamic_index_in_dim(y_c, ii, axis=1, keepdims=True)
    z_i = lax.dynamic_index_in_dim(z_c, ii, axis=1, keepdims=True)

    # Define the current flow field at this step
    u_sorted = u_init - turb_u_wake
    
    # Update turb_inflow for turbine ii
    # In FLORIS: u_i = flow_field.u_sorted[:, i:i+1]
    # We update turb_inflow so that lax.dynamic_index_in_dim(turb_inflow, ii) gives the current u_i
    turb_inflow = lax.dynamic_update_slice_in_dim(turb_inflow, u_sorted, ii, axis=1)

    u_i = lax.dynamic_index_in_dim(turb_inflow, ii, axis=1, keepdims=True)
    # print(f"u_i: {u_i}")
    # print(f"=== DiffWake Step {ii} ===")
    # print(f"Turbine inflow: {turb_inflow}")
    # print(f"Turb_u_wake: {turb_u_wake}")
    # jax.debug.print(
    #     "=== DiffWake Step {ii} ===\n"
    #     "  1. Turb_inflow       : {turb_inflow:.15f}\n"
    #     "  2. Turb_u_wake      : {turb_u_wake:.15f}\n",
    #     ii=ii,
    #     turb_u_wake=turb_u_wake,
    #     turb_inflow=turb_inflow,
    # )
    # Calculate average velocity for turbine ii from its inflow
    # turb_avg = average_velocity_jax(u_i)

    # vel_avg__i should be (B, 1, 1, 1)
    # vel_avg__i = turb_avg

    yaw_i = lax.dynamic_index_in_dim(yaw_angles, ii, axis=1, keepdims=True)
    tilt_i = lax.dynamic_index_in_dim(tilt_angles, ii, axis=1, keepdims=True)

    # print(f"u-vel: {u_i}")

    # Calculate thrust coefficients and axial induction
    turb_Cts_i = thrust_function(velocities = u_i,#vel_avg__i,
                                 yaw_angles = yaw_i,
                                 tilt_angles = tilt_i)[:, :, None, None]


    
    # We need axial_induction_i which is (B, 1, 1, 1)
    axial_i = axial_induction_func(
        turb_inflow, yaw_angles, tilt_angles, ix_filter=ii)  #
    # The axial_induction_func returns (B, 1), we need (B, 1, 1, 1)
    axial_i = axial_i[:, :, None, None]

    turb_aIs = axial_i

    u_i = lax.dynamic_index_in_dim(turb_inflow, ii, axis=1, keepdims=True)
    v_i = lax.dynamic_index_in_dim(v_sorted, ii, axis=1, keepdims=True)
    w_i = lax.dynamic_index_in_dim(w_sorted, ii, axis=1, keepdims=True)
    ti_i = lax.dynamic_index_in_dim(ti, ii, axis=1, keepdims=True)
    yaw_i_expanded = yaw_i[:, :, None, None]


    # Calculate secondary steering
    if enable_secondary_steering:
        y_coord_i = lax.dynamic_index_in_dim(y_coord, ii, axis=1, keepdims=True)
        z_coord_i = lax.dynamic_index_in_dim(z_coord, ii, axis=1, keepdims=True)

        added_yaw = wake_added_yaw(
            u_i, v_i, u_init,
            y_coord_i - y_i, z_coord_i,
            params.rotor_diameter, params.hub_height,
            turb_Cts_i, params.TSR, axial_i,
            params.wind_shear, scale=1.0
        )
        yaw_eff = yaw_i_expanded + added_yaw
        # print(f"Yaw_expanded: {yaw_i_expanded}")
        # print(f"Added yaw: {added_yaw}")
    else:
        yaw_eff = yaw_i_expanded
    # print(f"Yaw_eff before secondary: {yaw_i_expanded}")
    # print(f"Yaw_eff after secondary: {yaw_eff}")


    # Calculate wake deflection
    # print(f"Rotor diameter: {params.rotor_diameter}")
    # print(f"x_i: {x_i}")
    # print(f"yaw_eff: {yaw_eff}")
    # print(f"ti_i: {ti_i}")
    # print(f"turb_Cts_i: {turb_Cts_i}")
    # print(f"x_coord: {x_coord}")
    # print(f"U_free: {u_init}")
    # print(f"wind_veer: {params.wind_veer}")

    # jax.debug.print(
    #     "=== DiffWake Step {ii} ===\n"
    #     "  1. Inflow u_i (mean)       : {u_i_mean:.15f}\n"
    #     "  2. Thrust ct_i (mean)      : {ct_i_mean:.15f}\n"
    #     "  3. Axial Induction (mean)  : {a_i_mean:.15f}\n"
    #     "  4. Yaw eff (mean)          : {yaw_eff_mean:.15f}\n",
    #     ii=ii,
    #     u_i_mean=jnp.mean(u_i),
    #     ct_i_mean=jnp.mean(turb_Cts_i),
    #     a_i_mean=jnp.mean(turb_aIs),
    #     yaw_eff_mean=jnp.mean(yaw_eff)
    # )

    def_field = deflection_model(
        x_i, yaw_eff, ti_i, turb_Cts_i,
        params.rotor_diameter,
        x=x_coord,
        U_free=u_init, wind_veer=params.wind_veer
    )

    # print("DiffWake deflection: ", def_field)

    # Calculate transverse velocities
    # print(f"gridx: {x_coord - x_i}")
    # print(f"gridy: {y_coord - y_i}")
    # print(f"z: {z_coord}")
    # print(f"shear: {params.wind_shear}")

    v_wake, w_wake = lax.cond(
        enable_transverse_velocities,
        lambda: calculate_transverse_velocity(
            u_i, u_init, dudz_init,
            x_coord - x_i, y_coord - y_i, z_coord,
            params.rotor_diameter, params.hub_height,
            yaw_i_expanded, turb_Cts_i, params.TSR, axial_i,
            params.wind_shear, scale=1.0
        ),
        lambda: (jnp.zeros_like(v_sorted), jnp.zeros_like(w_sorted))
    )
    # print(f"v_wake: {v_wake}")
    # print(f"w_wake: {w_wake}")


    # Calculate yaw added recovery and update the TI field
    if enable_yaw_added_recovery:
        v_wake_i = lax.dynamic_index_in_dim(v_wake, ii, axis=1, keepdims=True)
        w_wake_i = lax.dynamic_index_in_dim(w_wake, ii, axis=1, keepdims=True)
        # print(f"u_i mean: {jnp.mean(u_i)}")
        # print(f"ti_i mean: {jnp.mean(ti_i)}")
        # print(f"v_i mean: {jnp.mean(v_i)}")
        # print(f"w_i mean: {jnp.mean(w_i)}")
        # print(f"v_wake_i mean: {jnp.mean(v_wake_i)}")
        # print(f"w_wake_i mean: {jnp.mean(w_wake_i)}")
        I_mixing = yaw_added_turbulence_mixing(
            u_i,
            ti_i,
            v_i,
            w_i,
            v_wake_i,
            w_wake_i
        )
        gch_gain = 2.0
        # print(f"I_mixing: {I_mixing}")
        # print(f"Ti_i: {ti_i}")

        updated = (ti_i + gch_gain * I_mixing).astype(ti.dtype)
        # Sanitization for gradient safety
        updated = jnp.nan_to_num(updated, nan=0.0, posinf=0.0, neginf=0.0)

        ti = lax.dynamic_update_slice_in_dim(ti, updated, ii, axis=1)
        # Update ti_i for use in velocity_model
        ti_i = updated


    # print(f"Turbine {ii} TI: {ti}")

    # Calculate the velocity deficit and combine it with the wake field
    velocity_deficit, _ = velocity_model(
        x_i, y_i, z_i,
        axial_i,
        def_field,
        yaw_i_expanded,
        ti_i,
        turb_Cts_i,
        params.hub_height,
        params.rotor_diameter,
        x=x_coord,
        y=y_coord,
        z=z_coord,
        u_initial=u_init,
        wind_veer=params.wind_veer
    )
    # print(f"vel def: {velocity_deficit}")

    # Accumulate the wake field
    # Combine GCH deficit into the existing wake
    wake_field, _ = combination_model(
        turb_u_wake,
        velocity_deficit * u_init,
    )


    # Calculate turbulence intensity
    wake_added_ti = turbulence_model(
        ambient_ti, x_coord, x_i, params.rotor_diameter, turb_aIs
    )

    # Calculate area overlap for wake-added turbulence (WAT)
    # FLORIS: np.sum(velocity_deficit * flow_field.u_initial_sorted > 0.05, axis=(2, 3)) / (grid_res**2)
    area_overlap = (
        jnp.sum(velocity_deficit * u_init > 0.05, axis=(2, 3)) /
        params.gr_square
    )

    dtype = x_coord.dtype
    downstream_len = 15.0 * params.rotor_diameter
    eps = jnp.asarray(1e-10, dtype)

    downstream_start = x_coord > (x_i + eps)
    downstream_end = x_coord <= (x_i + downstream_len - eps)
    down_mask = (downstream_start & downstream_end).astype(dtype)

    # Lateral wake mask
    dy = jnp.abs(y_coord - y_i)
    lat_mask = (dy < 2.0 * params.rotor_diameter - eps).astype(dtype)

    wake_ti = jnp.nan_to_num(wake_added_ti, nan=0.0, posinf=0.0, neginf=0.0)

    ao = area_overlap[:, :, None, None]

    ti_added = ao * wake_ti * down_mask * lat_mask

    ti = jnp.maximum(jnp.hypot(ti_added, ambient_ti), ti).astype(ti.dtype)

    # Additional transverse velocity from wake
    v_sorted = (v_sorted + v_wake).astype(v_sorted.dtype)
    w_sorted = (w_sorted + w_wake).astype(w_sorted.dtype)

    # jax.debug.print(
    #     "  5. Deflection Field (max)  : {defl_max:.18f}\n"
    #     "  6. Velocity Deficit (max)  : {def_max:.18f}\n"
    #     "  7. Acc. Wake Field (max)   : {wake_max:.18f}\n"
    #     "  8. Acc. TI Field (max)     : {ti_max:.18f}\n",
    #     defl_max=jnp.max(jnp.abs(def_field)),
    #     def_max=jnp.max(velocity_deficit),
    #     wake_max=jnp.max(wake_field),
    #     ti_max=jnp.max(ti)
    # )

    next_state = DynamicState(
        turb_u_wake=wake_field,
        turb_inflow=turb_inflow,
        ti=ti,
        v_sorted=v_sorted,
        w_sorted=w_sorted,
        Ctmp=None,
        ct_acc=None
    )

    return next_state, None


def cc_solver_step(
    state: DynamicState,
    ii: int,
    params: Params,
    thrust_function: Callable,
    axial_induction_func: Callable,
    velocity_model: Callable, 
    deflection_model: Callable,
    turbulence_model: Callable,
    yaw_angles: jnp.array,
    tilt_angles: jnp.array,
    enable_secondary_steering: bool,
    enable_transverse_velocities: bool,
    enable_yaw_added_recovery: bool,
    x_coord, y_coord, z_coord,
    x_c, y_c, z_c,
    u_init, dudz_init,
    ambient_ti
) -> Tuple[DynamicState, None]:

    """One turbine-index update; identical math to PyTorch version."""

    # ─── unpack state tensors ───────────────────────────────────────────
    turb_u_wake, turb_inflow, ti, v_sorted, w_sorted, Ctmp, ct_acc = (
        state.turb_u_wake, state.turb_inflow, state.ti,
        state.v_sorted,      state.w_sorted,      state.Ctmp, state.ct_acc
    )
    # ─── constants for turbine ii ───────────────────────────────────────
    B,T,N,N = x_coord.shape

    x_i = lax.dynamic_index_in_dim(x_c, ii, axis=1, keepdims=True)
    y_i = lax.dynamic_index_in_dim(y_c, ii, axis=1, keepdims=True)
    z_i = lax.dynamic_index_in_dim(z_c, ii, axis=1, keepdims=True)

    rad = 0.51 * params.rotor_diameter            # skalar/tensor
    mask_i = (
        (x_coord >  x_i - 0.01) & (x_coord < x_i + 0.01) &
        (y_coord >  y_i - rad ) & (y_coord < y_i + rad )
    )
    diff = u_init - turb_u_wake                  # (B,T,N,N)

    turb_inflow = jnp.where(mask_i, diff, turb_inflow)

    turb_avg = average_velocity_jax(turb_inflow)

    vel_avg__i  = lax.dynamic_index_in_dim(turb_avg,   ii, axis=1, keepdims=True)  # (B,1,1,1)
    yaw_i  = lax.dynamic_index_in_dim(yaw_angles, ii, axis=1, keepdims=True)  # (B,1)
    tilt_i = lax.dynamic_index_in_dim(tilt_angles,ii, axis=1, keepdims=True)  # (B,1)

    u_i_plane = lax.dynamic_index_in_dim(turb_inflow, ii, axis=1, keepdims=True)
    turb_Cts_i = thrust_function(velocities = vel_avg__i,
                               yaw_angles = yaw_i,
                               tilt_angles = tilt_i)[:,:,None, None]        # (B,T,1,1)


    ct_acc = lax.dynamic_update_slice_in_dim(ct_acc, turb_Cts_i, ii, axis=1)
    turb_aIs = axial_induction_func(
        turb_avg, yaw_angles, tilt_angles, ix_filter=ii)[:, :, None, None]       # (B,T,1,1)

    turb_aIs = turb_aIs

    axial_i = axial_induction_func(
        u_init, yaw_angles, tilt_angles, ix_filter=ii)[:, None, None]
    

    u_i  = lax.dynamic_index_in_dim(turb_inflow, ii, axis=1, keepdims=True)
    v_i  = lax.dynamic_index_in_dim(v_sorted, ii, axis=1, keepdims=True)    
    w_i  = lax.dynamic_index_in_dim(w_sorted, ii,axis=1, keepdims=True) 
    ti_i  = lax.dynamic_index_in_dim(ti, ii, axis=1, keepdims=True) 
    yaw_i = yaw_i[:, :, None, None]  # Now shape is (B, 1, 1, 1)

    # 3. secondary steering
    if enable_secondary_steering:
        y_coord_i = lax.dynamic_index_in_dim(y_coord, ii, axis=1, keepdims=True )
        z_coord_i = lax.dynamic_index_in_dim(z_coord, ii, axis=1, keepdims=True )
        added_yaw = wake_added_yaw(
            u_i, v_i, u_init,
            y_coord_i - y_i, z_coord_i,
            params.rotor_diameter, params.hub_height,
            turb_Cts_i, params.TSR, axial_i,
            params.wind_shear, scale=2.0
        )
           
        yaw_eff = yaw_i + added_yaw
    else:
        yaw_eff = yaw_i

    def_field = deflection_model(
        x_i, yaw_eff, ti_i, turb_Cts_i,
        params.rotor_diameter,
        x=x_coord,
        U_free=u_init, wind_veer=params.wind_veer
    )

    v_wake, w_wake = lax.cond(
        enable_transverse_velocities,
        lambda: calculate_transverse_velocity(
            u_i, u_init, dudz_init,
            x_coord - x_i, y_coord - y_i, z_coord,
            params.rotor_diameter, params.hub_height,
            yaw_i, turb_Cts_i, params.TSR, axial_i,
            params.wind_shear, scale=2.0
        ),
        lambda: (jnp.zeros_like(v_sorted), jnp.zeros_like(w_sorted))
    )


    if enable_yaw_added_recovery:
        v_wake_i = lax.dynamic_index_in_dim(v_wake, ii, axis=1, keepdims=True )
        w_wake_i = lax.dynamic_index_in_dim(w_wake, ii, axis=1, keepdims=True )

        I_mixing = yaw_added_turbulence_mixing(
            u_i, 
            ti_i, 
            v_i,
            w_i,
            v_wake_i, 
            w_wake_i
            )
        updated = (I_mixing + ti_i).astype(ti.dtype)
        #ti = lax.dynamic_update_slice(ti, updated, (0, ii, 0, 0))
        ti = lax.dynamic_update_slice_in_dim(ti, updated, ii, axis=1)
        
    turb_u_wake, Ctmp = velocity_model(
        ii, x_i, y_i, z_i, u_i,
        def_field, yaw_i, ti,
        ct_acc, params.rotor_diameter,
        turb_u_wake, Ctmp,
        x=x_coord, y=y_coord, z=z_coord, u_initial=u_init
    )
    # 6. turbulence intensity

    wake_added_ti = turbulence_model(
        ambient_ti, x_coord, x_i, params.rotor_diameter, turb_aIs
    )


    area_overlap = 1.0 - (
        jnp.sum(turb_u_wake <= 0.05, axis=(2, 3)) /
        params.gr_square
    )


    dtype = x_coord.dtype
    downstream_len = 15.0 * params.rotor_diameter
    eps = jnp.asarray(1e-10, dtype)

    downstream_start = x_coord > (x_i + eps)                         # bool
    downstream_end   = x_coord <= (x_i + downstream_len - eps)       # bool
    down_mask = (downstream_start & downstream_end).astype(dtype)    # 0/1

    # ------------------------------------------------ lateral-mask
    dy = jnp.abs(y_coord - y_i)
    lat_mask = (dy < 2.0 * params.rotor_diameter- eps).astype(dtype)           # 0/1

    # ------------------------------------------------ turbulence-bidrag
    wake_ti = jnp.nan_to_num(wake_added_ti, nan=0.0, posinf=0.0, neginf=0.0)

    # area_overlap kommer som (B,1); broadcasta till (B,1,1,1)
    ao = area_overlap[:, :, None, None]

    ti_added = ao * wake_ti * down_mask * lat_mask

    # identisk formel: sqrt( ti_added² + ambient² ), sedan max med befintlig

    ti = jnp.maximum(jnp.sqrt(ti_added**2 + ambient_ti**2), ti).astype(ti.dtype)

    # ------------------------------------------------ addera sidvind-fält
    v_sorted = (v_sorted + v_wake).astype(v_sorted.dtype)
    w_sorted = (w_sorted + w_wake).astype(w_sorted.dtype)
    next_state = DynamicState(
        turb_u_wake=turb_u_wake,
        turb_inflow=turb_inflow,
        ti=ti,
        v_sorted=v_sorted,
        w_sorted=w_sorted,
        Ctmp=Ctmp,
        ct_acc = ct_acc
    )
    return next_state, None


def turbopark_solver() -> Tuple[DynamicState, None]:
    # Needs writing
    pass


def empirical_gauss_solver() -> Tuple[DynamicState, None]:
    # Needs writing
    pass

